### ISSUE TITLE
Fix possibility to select different chipselect with pyftdi>=0.40

### ISSUE THREAD

**Issue by j123b567** [eblot/pyspiflash#15]
pyftdi>=0.40 changes default number of chipselects from 4 to 1. Chipselect number can be passed to method `SerialFlashManager.get_flash_device()`, but it no longer works for cs>0, because `SpiController` must be initialised with propper number of available chipselects, which cant be done.

May be related to #1

**Comment by eblot** [comment]
Upcoming pyspiflash will support this new API.

I wrote the code this afternoon, but I did not have the HW at end to run a minimal test session.

**Comment by eblot** [comment]
Now addressed in v0.6.0

**Comment by eblot** [comment]
See spiflash/tests/serialflash.py for example.

**Comment by j123b567** [comment]
You are fast! Thank you.
