### ISSUE TITLE
Examples, please

### ISSUE THREAD

**Issue by ferdas** [eblot/pyspiflash#6]
Hello guys :)

I stumbled upon this interesting project because I'm experimenting a bit with flash memories (MX25L12835F). I'd like to make it work and then to make a pull request to add the support of this IC (in case I succed, I mean ^^").

I would be really grateful if you could share a basic example of how to use this library.
Thank you in advance!

**Comment by eblot** [comment]
You could start up with the unit test file (spiflash/tests/serialflash.py)

**Comment by ferdas** [comment]
Thank you :)
