### ISSUE TITLE
/dev/spidevX.X

### ISSUE THREAD

**Issue by BTOdell** [eblot/pyspiflash#7]
How do I use this Python library to interact with a flash chip that is reachable at the Linux device: /dev/spidevX.X?
It seems like the only way is through this URL scheme: https://eblot.github.io/pyftdi/urlscheme.html

**Comment by eblot** [comment]
Sorry, I forgot to answer and it is likely not relevant anymore, anyway:

/dev/spidev is a Linux-managed flash device, while pyspiflash is dedicated to manage flash device on a SPI bus which is mastered with a FTDI device.

I guess pyspiflash could be adapted to use a local device, but it is out of scope of the current project. Sorry.
